export enum ArticleCategory {
    POLITICS = 'POLITICS',
    TECHNOLOGY = 'TECHNOLOGY',
    SCIENCE = 'SCIENCE',
    HEALTH = 'HEALTH',
    ENTERTAINMENT = 'ENTERTAINMENT',
    SPORTS = 'SPORTS',
    BUSINESS = 'BUSINESS',
    OTHER = 'OTHER',
} 