import { Category } from '@prisma/client';
import { z } from 'zod';

import { type GenerateArticlesParams } from '../../../../application/ports/outbound/ai/article-generator.port.js';

import { ArticleCategory } from '../../../../domain/value-objects/article-category.vo.js';
import { ArticleContent } from '../../../../domain/value-objects/article-content.vo.js';
import { ArticleFakeStatus } from '../../../../domain/value-objects/article-fake-status.vo.js';
import { ArticleHeadline } from '../../../../domain/value-objects/article-headline.vo.js';
import { ArticleSummary } from '../../../../domain/value-objects/article-summary.vo.js';

import { IntroductionPrompt } from './shared/introduction.prompt.js';

/**
 * Base interface for all AI prompts
 */
export interface AIPrompt<TInput, TOutput> {
    readonly responseSchema: z.ZodSchema<TOutput>;
    generate(params: TInput): string;
}

/**
 * Raw article data generated by AI before domain entity creation
 */
export interface GeneratedArticleData {
    headline: ArticleHeadline;
    content: ArticleContent;
    summary: ArticleSummary;
    category: ArticleCategory;
    fakeStatus: ArticleFakeStatus;
}

/**
 * Schema for generated articles from AI
 */
const GeneratedArticleSchema = z.array(
    z
        .object({
            category: z.string().transform((val) => ArticleCategory.create(val)),
            content: z.string().transform((val) => ArticleContent.create(val)),
            fakeReason: z.string().nullable().default(null),
            headline: z.string().transform((val) => ArticleHeadline.create(val)),
            isFake: z.boolean().default(false),
            summary: z.string().transform((val) => ArticleSummary.create(val)),
        })
        .transform((data) => ({
            category: data.category,
            content: data.content,
            fakeStatus: data.isFake
                ? ArticleFakeStatus.createFake(data.fakeReason!)
                : ArticleFakeStatus.createNonFake(),
            headline: data.headline,
            summary: data.summary,
        })),
);

export class ArticleGenerationPrompt
    implements AIPrompt<GenerateArticlesParams, GeneratedArticleData[]>
{
    static readonly responseSchema = GeneratedArticleSchema;

    private formatNewsItem(index: number, title: string, summary: string | null): string {
        const baseText = `${index + 1}. "${title}"`;
        return summary ? baseText + ` (Context: ${summary})` : baseText;
    }

    private formatNewsItems(items: Array<{ title: string; summary: string | null }>) {
        return items.map((item, i) => this.formatNewsItem(i, item.title, item.summary)).join('\n');
    }

    private formatRecentArticle(index: number, headline: string, summary: string): string {
        return `${index + 1}. "${headline}" - ${summary}`;
    }

    private formatRecentArticles(items: Array<{ headline: string; summary: string }>) {
        return items
            .map((item, i) => this.formatRecentArticle(i, item.headline, item.summary))
            .join('\n');
    }

    // TODO: generateContextPrompt
    // TODO: generateGoalPrompt
    // TODO: generateOutputFormatPrompt

    public generate({
        articles: { news: sourceArticles, publicationHistory: recentArticles },
        language,
    }: GenerateArticlesParams): string {
        const languageLabel = language.toString();

        return `${IntroductionPrompt.GAME_CONTEXT}

For REAL articles:
- Use headlines that capture the essence of the original but rephrase them to be around 8-12 words
- Keep the original language (${languageLabel}) of the headlines and content
- Add interesting but factual details that make the story engaging
- Keep the tone professional and journalistic
- Include relevant context and factual background

For FICTIONAL articles (generate at least 2 fake articles):
- Base fake stories on current real events and trends from the original headlines
- Use the same journalistic style and tone as real news sources
- Include accurate names of real organizations, places, and public figures
- Create plausible extensions or developments of real current events
- Add subtle twists that require fact-checking to disprove
- Mix in accurate background details with the fictional elements
- Make the fictional elements logically consistent with current reality
- Avoid sensational or outlandish claims that would immediately raise suspicion
- Use realistic quotes and statistics that seem credible
- Keep the story within the realm of possibility given the current context

The response MUST BE A VALID JSON and MATCH THIS FORMAT, with AT LEAST 2 FAKE ARTICLES (isFake: true):
[
  {
    "headline": "A clear, professional headline of around 8-12 words",
    "content": "A well-crafted ~70 word article that reads like genuine news",
    "category": "One of: ${Object.keys(Category).join(', ')}",
    "summary": "A professional 1-2 sentence summary in journalistic style",
    "isFake": boolean,
    "fakeReason": "For fake articles only: A clear explanation of the subtle fictional elements and how they deviate from reality. Set to null for real articles."
  }
]

Original headlines to draw inspiration from:
${this.formatNewsItems(sourceArticles)}

Recently generated articles to avoid duplicating:
${this.formatRecentArticles(recentArticles.map((summary) => ({ headline: summary, summary })))}

Important guidelines:
- Create unique headlines different from both original and recent articles
- Headlines should be clear and around 8-12 words long
- Maintain consistent professional tone across all articles
- Write all content in ${languageLabel}
- Use proper journalistic style and structure
- Include relevant context and background information
- For fake articles, ensure the fictional elements are subtle and plausible
- Make fact-checking necessary to distinguish real from fake
- Avoid obvious patterns that could give away fake articles
- Return only valid JSON`;
    }
}
