app:
  env: NODE_ENV
  port: PORT
  host: HOST
  newRelic:
    licenseKey: NEW_RELIC_LICENSE_KEY
  databaseUrl: DATABASE_URL

logging:
  level: LOG_LEVEL

api:
  openRouter:
    apiKey: OPEN_ROUTER_API_KEY
  worldNews:
    apiKey: WORLD_NEWS_API_KEY
