app:
  env: development
  port: 3000
  host: localhost
  newRelic:
    enabled: true
  databaseUrl: file:./database/main.sqlite

logging:
  level: info
  prettyPrint: true

api:
  openRouter:
    budget: paid
  worldNews:
    useCache: false
