inbound:
  env: production
  http:
    host: localhost
    port: 3000
  logger:
    level: info
    prettyPrint: false

outbound:
  openRouter:
    budget: paid
  worldNews:
    useCache: false
  newRelic:
    enabled: true
