inbound:
  env: development
  http:
    host: localhost
    port: 3000
  logger:
    level: info
    prettyPrint: true

outbound:
  prisma:
    databaseUrl: file:./database/main.sqlite
  openRouter:
    budget: paid
  worldNews:
    useCache: false
  newRelic:
    enabled: true
