inbound:
  http:
    port: 3000
  logger:
    level: debug
    prettyPrint: true
  tasks:
    articleGeneration:
      - country: fr
        language: fr
    storyDigest:
      - country: fr
        language: fr

outbound:
  openRouter:
    budget: low
  worldNews:
    useCache: true
