inbound:
  env: test
  http:
    host: localhost
    port: 3000
  logger:
    level: debug
    prettyPrint: true

outbound:
  prisma:
    databaseUrl: file:./database/test.sqlite
  openRouter:
    apiKey: test-openrouter-key
    budget: low
  worldNews:
    apiKey: test-world-news-key
  newRelic:
    enabled: false
