app:
  env: test
  port: 3000
  host: localhost
  newRelic:
    enabled: false

logging:
  level: debug

api:
  worldNews:
    apiKey: test-world-news-key
  openRouter:
    apiKey: test-openrouter-key
    budget: free
